# -*- coding: utf-8 -*-
"""socialadslogisticregression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c9bR7bwxUUWIgcF2tjRQWNFU1LGKqcmx
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv('Social_Network_Ads.csv')

df.shape

df.isnull().sum();

df

x = df.iloc[:,2:4].values

y = df.iloc[:,4].values

from sklearn.model_selection import train_test_split;
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

x_train.shape

from sklearn.linear_model import LogisticRegression
reg = LogisticRegression();
reg.fit(x_train,y_train);

y_predict = reg.predict(x_test)



comp=pd.DataFrame({"Actual":y_test,"Predicted":y_predict});

comp

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_predict)

cm

